(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();let m=0,p=null,g="",I=[];async function M(){try{const c=document.querySelector(".events-list");c&&(c.innerHTML='<div style="display: flex; justify-content: center; align-items: center; min-height: 400px; font-size: 24px; font-weight: bold; color: #666;">Loading all pages<span style="display: inline-block; margin-left: 10px; animation: spin 1s linear infinite;"></span></div>');let o=[];const r=51,l=3;console.log(`Завантажую ${r} сторінок...`);for(let e=0;e<r;e+=l){const t=Math.min(e+l,r),s=[];for(let n=e;n<t;n++){const a=`https://app.ticketmaster.com/discovery/v2/events.json?apikey=Q8bHL81HES4CjxatVZAVSQWYyAffYhbQ&page=${n}`;s.push(fetch(a,{signal:AbortSignal.timeout(1e4)}).then(d=>d.json()).then(d=>{var y;const u=((y=d._embedded)==null?void 0:y.events)||[];return console.log(`✓ Сторінка ${n+1}/${r} - ${u.length} подій`),u}).catch(d=>(console.log(`⚠ Сторінка ${n+1}: ${d.message}`),[])))}(await Promise.all(s)).forEach(n=>{o=o.concat(n)}),await new Promise(n=>setTimeout(n,100))}return console.log(`✅ Готово! Завантажено ${o.length} подій з ${r} сторінок`),o}catch(c){return console.log("Критична помилка:",c),[]}}function q(){let c=I;if(p&&(c=c.filter(o=>{var l,e,t,s;return((s=(t=(e=(l=o._embedded)==null?void 0:l.venues)==null?void 0:e[0])==null?void 0:t.country)==null?void 0:s.name)===p})),g){const o=g.toLowerCase();c=c.filter(r=>{var s,i,n,a,d;const l=(r.name||"").toLowerCase(),e=(((n=(i=(s=r._embedded)==null?void 0:s.venues)==null?void 0:i[0])==null?void 0:n.name)||"").toLowerCase(),t=((d=(a=r.dates)==null?void 0:a.start)==null?void 0:d.localDate)||"";return l.includes(o)||e.includes(o)||t.includes(o)})}return c}function f(c=0){const o=document.querySelector(".events-list"),r=document.getElementById("page-info");if(!o)return;const l=q(),e=20,t=c*e,s=t+e,i=l.slice(t,s);let n="";if(i.forEach(a=>{var h,v,E,L,$,b,P,S,w,x,C;const d=((v=(h=a.images)==null?void 0:h[0])==null?void 0:v.url)||"",u=a.name||"Без названия",y=((L=(E=a.dates)==null?void 0:E.start)==null?void 0:L.localDate)||"Дата невідома",A=((P=(b=($=a._embedded)==null?void 0:$.venues)==null?void 0:b[0])==null?void 0:P.name)||"Місце невідоме",_=((C=(x=(w=(S=a._embedded)==null?void 0:S.venues)==null?void 0:w[0])==null?void 0:x.country)==null?void 0:C.name)||"Unknown";n+=`
      <li class="event-card" data-country="${_}">
        <img class="event-img" src="${d}" alt="${u}">
        <h3 class="event-title">${u}</h3>
        <p class="event-date">${y}</p>
        <p class="event-place">${A}</p>
      </li>
    `}),o.innerHTML=n,r){const a=Math.ceil(l.length/e);r.textContent=`Page ${c+1} of ${a}`}m=c}document.addEventListener("DOMContentLoaded",async()=>{I=await M(),f(0);const c=document.querySelector(".header__input");c&&c.addEventListener("input",s=>{g=s.target.value,f(0)});const o=document.getElementById("prev");o&&o.addEventListener("click",()=>{m>0&&f(m-1)});const r=document.getElementById("next");r&&r.addEventListener("click",()=>{const s=q(),i=20,n=Math.ceil(s.length/i);m<n-1&&f(m+1)});const l=document.querySelector(".country-dropdown"),e=document.querySelector(".country-selected"),t=document.querySelector(".country-menu");l&&e&&t&&(e.addEventListener("click",()=>{l.classList.toggle("open")}),t.querySelectorAll("div").forEach(i=>{i.addEventListener("click",()=>{const n=i.dataset.country;n===""?(p=null,e.textContent="Choose country"):(p=n,e.textContent=n),l.classList.remove("open"),f(0)})}),document.addEventListener("click",i=>{l.contains(i.target)}))});
//# sourceMappingURL=commonHelpers.js.map
