(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();let u=0,m=null,p="",C=[];async function q(){var o;let c=0,n=[],r=!0;for(;r;){const e=`https://app.ticketmaster.com/discovery/v2/events.json?apikey=Q8bHL81HES4CjxatVZAVSQWYyAffYhbQ&page=${c}`;try{const a=((o=(await(await fetch(e)).json())._embedded)==null?void 0:o.events)||[];n=n.concat(a),a.length<20&&(r=!1),c++}catch(t){console.log("Помилка завантаження:",t),r=!1}}return n}function I(){let c=C;if(m&&(c=c.filter(n=>{var o,e,t,s;return((s=(t=(e=(o=n._embedded)==null?void 0:o.venues)==null?void 0:e[0])==null?void 0:t.country)==null?void 0:s.name)===m})),p){const n=p.toLowerCase();c=c.filter(r=>{var s,a,l,i,f;const o=(r.name||"").toLowerCase(),e=(((l=(a=(s=r._embedded)==null?void 0:s.venues)==null?void 0:a[0])==null?void 0:l.name)||"").toLowerCase(),t=((f=(i=r.dates)==null?void 0:i.start)==null?void 0:f.localDate)||"";return o.includes(n)||e.includes(n)||t.includes(n)})}return c}function d(c=0){const n=document.querySelector(".events-list"),r=document.getElementById("page-info");if(!n)return;const o=I(),e=20,t=c*e,s=t+e,a=o.slice(t,s);let l="";if(a.forEach(i=>{var g,v,h,E,L,P,w;const f=((v=(g=i.images)==null?void 0:g[0])==null?void 0:v.url)||"",y=i.name||"Без названия",b=((E=(h=i.dates)==null?void 0:h.start)==null?void 0:E.localDate)||"Дата невідома",S=((w=(P=(L=i._embedded)==null?void 0:L.venues)==null?void 0:P[0])==null?void 0:w.name)||"Місце невідоме";l+=`
      <li class="event-card">
        <img class="event-img" src="${f}" alt="${y}">
        <h3 class="event-title">${y}</h3>
        <p class="event-date">${b}</p>
        <p class="event-place">${S}</p>
      </li>
    `}),n.innerHTML=l,r){const i=Math.ceil(o.length/e);r.textContent=`Page ${c+1} of ${i}`}u=c}document.addEventListener("DOMContentLoaded",async()=>{C=await q(),d(0);const c=document.querySelector(".header__input");c&&c.addEventListener("input",s=>{p=s.target.value,d(0)});const n=document.getElementById("prev");n&&n.addEventListener("click",()=>{u>0&&d(u-1)});const r=document.getElementById("next");r&&r.addEventListener("click",()=>{const s=I(),a=20,l=Math.ceil(s.length/a);u<l-1&&d(u+1)});const o=document.querySelector(".country-dropdown"),e=document.querySelector(".country-selected"),t=document.querySelector(".country-menu");o&&e&&t&&(e.addEventListener("click",()=>{o.classList.toggle("open")}),t.querySelectorAll("div").forEach(a=>{a.addEventListener("click",()=>{const l=a.dataset.country;l===""?(m=null,e.textContent="Choose country"):(m=l,e.textContent=l),o.classList.remove("open"),d(0)})}),document.addEventListener("click",a=>{o.contains(a.target)}))});
//# sourceMappingURL=commonHelpers.js.map
